require ('./serverTest.js');
require ('./configValidationTest.js');
require ('./components/extractFieldsTest.js');
require ('./components/extractFieldsLocalizedNameTest.js');
require ('./components/loadJSONTest.js');
require ('./components/simplifyGeometryTest.js');
require ('./components/isActiveRecordTest.js');
require ('./components/filterOutNamelessRecordsTest.js');
require ('./components/filterOutUnimportantRecordsTest.js');
